### PR TITLE
Update generate.sql

### PR DESCRIPTION
**Pull request by hjubb**
is this how I pgsql?

~~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~

### CODE REVIEW

**Comment by hjubb** [comment]
@byronmejia **bump**

**Review by byronmejia — COMMENTED** [review]
Very nice code! 10/10

**Comment by byronmejia** [comment]
Very Nice

**Comment by hjubb** [comment]
Contact me at https://fb.me/publicstaticfinalString if you need anything else !

**Pull request merged**
